fun main(args: Array<String>) {

    val conan = Player("Conan")
    conan.getLoot(Loot("Invisibility", LootType.POTION, 4.0))
    conan.getLoot(Loot("Mithril", LootType.ARMOUR, 183.0))
    conan.getLoot(Loot("Ring of Speed", LootType.RING, 25.0))
    conan.getLoot(Loot("Red Potion", LootType.POTION, 2.0))
    //conan.getLoot(Loot("Cursed Shield", LootType.ARMOUR, -8.0))
    conan.getLoot(Loot("Brass Ring", LootType.RING, 1.0))
    conan.getLoot(Loot("Chain Mail", LootType.ARMOUR, 4.0))
    conan.getLoot(Loot("Gold Ring", LootType.ARMOUR, 12.0))
    conan.getLoot(Loot("Gold Ring", LootType.ARMOUR, 12.0))
    conan.getLoot(Loot("Gold Ring", LootType.ARMOUR, 12.0))
    conan.getLoot(Loot("Health Potion", LootType.POTION, 3.0))
    conan.getLoot(Loot("Silver Ring", LootType.RING, 6.0))
    conan.getLoot(Loot("Silver Ring", LootType.RING, 6.0))
    conan.showInventory()
    conan.dropLoot("Gold Ring")
    conan.showInventory()
    conan.dropLoot("Silver Ring")
    conan.showInventory()
    conan.dropLoot("Ring")
    conan.showInventory()
}